language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
     provider: heroku
     app: project1_travis
     on: master
     skip_cleanup: true
     api_key:
      secure: XSDZkpz0leXyYrAEfVIaYxYuCwSyL0jAl7MP2u7nzV7bfwQX9+qWuOfCTpDlGCKA2LHXtSkA8RVAh65vv1Li2QmlQdtHeL7SvDa5vJnnMM0WZb02vdqSHi+n+1Ei6v1M59oCZdck7xXz+ZtXqzEbB/Bq2927/hxJWubnfUwqkWk/WAKzfWuAghs7RSVNTQ8V2B/0FIiOhi/ob2vxF5JEaoxyJaAOQGF4h7MRqW+TrbPFX/XmMcJq077vWR5c9S9Do/l1kT4FckVtbfpBIJ18MTRlTOuwX5ePFHlVKgmWbzDa1iXA8VhgHiyPzjp+Tg7G6y9yDhPhzwOISsYVmaYLlKOLagbpvfC2SDD9UDW08d2NfwkPYo6fvQrHWQTINvlqjmN556H5pNuoLoVL1W9yFuCpgby5K7bCLYwn4yZahEXRV+4Kq1aeMcDA37ktWAsJPKtI7r+G0JAbQZVFAbtqg9tr96j5ZiNjLTa8LG9pSRPGppnucDf9lQFxv6Gf4/5RhzEjKUZux0G+Wj/HvnWxrZnnMqHYo9cqAs9jfxTJUEpOTPr7L9L7UVR+MQzp+9fbBPkhIlouo2EJtMQ0t9T3GO33hSPxbc0U3d7Ocj6kPQlVtSnqJQ3jmMHu+lFdjJWP3TSNsDI6kWmymoQZZyVoZcfpR4oOgxOdK6XKSRvnTuc=
